---
title: Aman Kumar Garg
baseurl: "/amank90theme"
desc: My blog post
about: I am a graduate at UBC. I am enrolled in Master in Data Science program of UBC 
image: https://avatars0.githubusercontent.com/u/13175313?s=400&u=82252faf6ee7e2875418292d993dec9db30d3ac4&v=4
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
